### ISSUE TITLE
domain Regex wrong

### ISSUE THREAD

**Issue by PowerChaos** [Antiun/odoo-reverse-proxy-howto#3]
hi,
after some testing i figured out the regex for the domain is wrong

i use a proxy to forward to intern ip adress

domain.com -> 10.x

with the regex ^%h$ it keeps asking me for a new db creation no mather what i give up

following fixed it = ^%d$

can you update this in your tutorial please
Thank you
Greets From PowerChaos

**Comment by antespi** [comment]
There are two options for db_filter:

**Option A**:

```
dbfilter=^%h$
```

In this case, if your domain is `10.example.com` the the database must be named `10_example_com`

**Option B**:

```
dbfilter=^%d$
```

In this case, if your domain is `10.example.com` the the database must be named `10`

This configuration parameter is full explained in Odoo documentation: https://www.odoo.com/documentation/8.0/setup/deploy.html
